export const STATUS_ONLINE: string = 'online'
export const DESKTOP: string = 'desktop'
export const EVENT_MESSAGE: string = 'message'
export const DIRECT_MESSAGE: string = 'dm'
export const BOT_OWNER: string = '164537364092289024'
